### ISSUE TITLE
after install and run the js-to-ts getting command not found

### ISSUE THREAD

**Issue by balr404** [stonelasley/javascript-to-typscript#1]
I did install 
$ npm install javascript-to-typescript

then i went to the root folder and type below command . noting works
user1 $ js-to-ts
-bash: js-to-ts: command not found

tell me how to set "js-to-ts" bash command.

**Comment by davidgxxl** [comment]
Same here.

In archlinux and windows 10

**Comment by deniercounter** [comment]
Unfortunately it is not working anymore out-of-the-box on windows 10 after having installed in Git-Bash with "npm i javascript-to-typescript -D" (with -D for installing as dev-dependencies). Would have been a cool migrating feature... but honestly who can believe that a converter could recognize the correct types. Too good to be true ;)

**Comment by minoseah629** [comment]
is there any update on this issue? as of 5/8/18

**Comment by keerthivasan12** [comment]
I followed the documentation is not working and i have some question to ask.
is it possible to convert javascript  to typescript ?
if it is possible means how ?
